### ISSUE TITLE
Nothing happens after I authorize in browser

### ISSUE THREAD

**Issue by brianjmurrell** [8bitgentleman/fitexport#1]
Hi.  I'm trying to give your app a spin.  I have a project set up a Google and am able to get through the OAuth bit where I am asked to authorize with my project.

Your app though just sits at:

```
Opening in existing browser session.
```

after I have authorized and closed my browser tab.  Eventually it stops with:

```
Traceback (most recent call last):
  File "/net/server/src/gpx2fit/fitexport/main.py", line 87, in <module>
    main()
  File "/net/server/src/gpx2fit/fitexport/main.py", line 61, in main
    execute()
  File "/usr/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/googleapiclient/http.py", line 922, in execute
    resp, content = _retry_request(
  File "/usr/lib/python3.10/site-packages/googleapiclient/http.py", line 221, in _retry_request
    raise exception
  File "/usr/lib/python3.10/site-packages/googleapiclient/http.py", line 190, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/usr/lib/python3.10/site-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/usr/lib/python3.10/site-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python3.10/site-packages/httplib2/__init__.py", line 1363, in _conn_request
    conn.connect()
  File "/usr/lib/python3.10/site-packages/httplib2/__init__.py", line 1153, in connect
    sock.connect((self.host, self.port))
TimeoutError: timed out
```

Any ideas?

**Comment by brianjmurrell** [comment]
NVM.  Seemed to be a local networking issue.
